name: ediscount
description: e-Discount Apps for Otsuka
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  http: ^0.13.4
  flutter_bloc: ^7.0.0
  equatable: ^2.0.3
  get_it: ^7.2.0
  retrofit_generator: ^6.0.0+2
  build_runner: ^2.3.3
  json_serializable: any
  json_annotation: ^4.6.0
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3
  flutter_dotenv: ^5.0.2
  intl: ^0.17.0
  timer_builder: ^2.0.0
  url_launcher: ^6.0.20
  path_provider: ^2.0.9
  flutter_spinkit: ^5.2.0
  stepper_list_view: ^0.0.1
  awesome_snackbar_content: ^0.1.1
  rename: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
     # images
     - assets/images/Login_background.svg
     - assets/images/logo.png

    # icons
     - assets/icons/ic_cancel.png
     - assets/icons/ic_check.png
     - assets/icons/ic_warning.png
     - assets/icons/ic_profile.png
     - assets/icons/ic_empty.png

  fonts:
     - family: book
       fonts:
         - asset: fonts/CircularStd-Book.ttf
     - family: bold
       fonts:
         - asset: fonts/CircularStd-Bold.ttf
     - family: medium
       fonts:
         - asset: fonts/CircularStd-Medium.ttf

